### ISSUE TITLE
Unable to load shared library 'libadwaita-1.so.0'

### ISSUE THREAD

**Issue by GlacierFox** [DevToys-app/DevToys#1322]
### Current behavior

Hi! Just downloaded the latest **devtoys_linux_x64_portable.zip** from the releases page and I'm getting an error when I'm trying to boot it.

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Adw.Application' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libadwaita-1.so.0' or one of its dependencies. In order to help diagnose loading problems, consider using a tool like strace. If you're using glibc, consider setting the LD_DEBUG environment variable: 
/home/danny/Apps/DevToys/libadwaita-1.so.0: cannot open shared object file: No such file or directory
/home/danny/Apps/DevToys/liblibadwaita-1.so.0: cannot open shared object file: No such file or directory
/home/danny/Apps/DevToys/libadwaita-1.so.0.so: cannot open shared object file: No such file or directory
/home/danny/Apps/DevToys/liblibadwaita-1.so.0.so: cannot open shared object file: No such file or directory

   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
   at Adw.Internal.ImportResolver.Resolve(String libraryName, Assembly assembly, Nullable`1 searchPath)
   at System.Runtime.InteropServices.NativeLibrary.LoadLibraryCallbackStub(String libraryName, Assembly assembly, Boolean hasDllImportSearchPathFlags, UInt32 dllImportSearchPathFlags)
   at Adw.Internal.Functions.Init()
   at Adw.Module.Initialize()
   at Adw.Application..cctor()
   --- End of inner exception stack trace ---
   at Adw.Application.New(String applicationId, ApplicationFlags flags)
   at DevToys.Linux.LinuxProgram..ctor() in /home/etienne/Documents/repos/Publish/submodules/DevToys/src/app/dev/platforms/desktop/DevToys.Linux/LinuxProgram.cs:line 34
   at DevToys.Linux.Program.Main(String[] args) in /home/etienne/Documents/repos/Publish/submodules/DevToys/src/app/dev/platforms/desktop/DevToys.Linux/Program.cs:line 9
Aborted (core dumped)
```

### How to reproduce it (as minimally and precisely as possible)

- Download the latest protable linux release.
- Try to run it.

### Expected behavior

For the app to run as normal.

### Affected platforms

Linux

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

v2.0.4.0

**Comment by badcel** [comment]
Hi, you need to have libadwaita installed.

**Comment by badcel** [comment]
Sorry I can't help you with this question as I never used RHEL myself.

But if they ship GNOME I would think that they ship WebKit, as it is used for Epiphany (aka GNOME Web) and probably Evolution (Email Client).

There was some incompatible API break in WebKit several years ago. You need to have this new version (the one you mentioned).

**Comment by GlacierFox** [comment]
@badcel ah thanks for the help anyway. It's probably due to RHEL having old packages or something. It does ship with GNOME by default but it's probably quite a bit behind the more up to date distributions.

**Comment by veler** [comment]
Hi @badcel ,

Thanks for helping finding a solution for @GlacierFox . Do you have any recommendation for me on how to handle this in the future? I'm thinking perhaps the app could try to detect on startup whether the dependencies are installed, and let the user know what he should do if they're not. I'm not exactly sure how to do that in an efficient (performance-proof) manner though.

What do you think?

**Comment by badcel** [comment]
Hi,

this is not an easy question. It depends on your Linux strategy:

- If you want to publish some portable version you probably want to check if some dependencies are missing and report this clearly to the user. This approaches probably is the most uncommon one for Linux users and developers: Even if you check for the dependencies as far as I know different distributions package their binaries in packages which can have different names or binaries can be grouped together in packages. Additionally binaries can be compiled with different compiler flags or feature sets enabled. And just because it can even get more complex, the names of the binaries themself can vary between distributions. I think all this stuff got better over time and distributions get more similar over time as there are standards which for example define which kind of binaries should be in which folder (which was different between distros, too). So in theory you could check what is missing and either detect if there is some alternative available or let the user configure it or similar. But GirCore currently is build for the GNOME flatpack runtime. This means there is a very specific binary name expected. Either it matches or not. I'm open to allow to define alternative binary names but won't support automatic detection by GirCore. Additionally this feature would need to be contributed as it would be totally unsupported from my side. Using some random binaries with nuget packages build for a certain target will have a whole lot more of potential problems which are fully located on the users side. I'm not willing to spend this time to investigate problems. There were already some discussions but those users were better of compiling their own custom GirCore binaries as they control the whole distribution stack (windows OS).
- A more common approach is to provide packages like you already do. Here similar problems apply like before but on a smaller scale because you can define your dependencies. But again those names can vary between distributions and creating for example a `*.deb` makes life harder for distros using different package manager like rpm / pacman / ...
- From my point of view the most developer friendly eco system is flatpak. There are flatpak runtimes (e.g. GNOME SDK), which bundle certain libraries like the standard gnome stack. Those don't get distributed with your package as it depends on the runtime which can be updated separately. This system ensures the user can get security updates without forcing yourself to watch all dependencies. At the same time you can be sure that all dependencies are available on any host independently of the distribution. So no matter if it is rpm or apt based, or having no GNOME installation at all it just works. An alternative would be snap which is a lot more coupled to Ubuntu (probably more in people's mind than in reality). I don't have any experience with it as it is quite uncommon to use for fedora. Of course there are people who don't like snap and there are people who don't like flatpak and there are people who don't like both. From my point of view flatpak is the way to go as it more spread across distros, solves a lot of problems, provides a central store (flathub) and enables developers to take application distribution into their own hands.

**Comment by probonopd** [comment]
Please avoid using libadwaita. [libadwaita doesn't work well](https://www.youtube.com/watch?v=WFqJA1q-IKY) outside of the Gnome desktop, reduing the potential user base for this application.

**Comment by badcel** [comment]
> Please avoid using libadwaita. [libadwaita doesn't work well](https://www.youtube.com/watch?v=WFqJA1q-IKY) outside of the Gnome desktop, reduing the potential user base for this application.

Can you open a separate issue for this as it is not related to this report.

**Comment by veler** [comment]
Hi, I have a PR here that should help with this issue: https://github.com/DevToys-app/DevToys/pull/1380
