### ISSUE TITLE
DevToys GUI crashes on Ubuntu 24.04

### ISSUE THREAD

**Issue by giosal** [DevToys-app/DevToys#1341]
### Current behavior

After installing DevToys GUI version using .deb file, I'm not able to launch it using the icon.
When I try to launch it from terminal using `devtoys` it also crashes with the following error:
```
bwrap: setting up uid map: Permission denied

** (DevToys:70971): ERROR **: 16:56:37.493: Failed to fully launch dbus-proxy: Child process exited with status 1
Terminated (core dumped)
```

However it launches with sudo

### How to reproduce it (as minimally and precisely as possible)

Install DevToys GUI using
`sudo dpkg -i devtoys_linux_x64.deb`

Launch from icon or from shell without sudo

### Expected behavior

Launch without errors

### Workaround

Launch from shell using sudo

### Affected platforms

Linux x64 / Ubuntu 24.04

### Affected DevToys kind

DevToys (app with GUI)

### DevToys Version

2.0-preview4

### Relevant Assets/Logs

```
2024-07-25T16:57:42.1919597+02:00	Information	[DevToys.Core.FileHelper]	[0]	Cleared temp files in 0.4124ms
2024-07-25T16:57:42.1978727+02:00	Information	[DevToys.Core.Mef.MefComposer]	[LogDiscoveringPlugin]	Discovering plugin in '/opt/devtoys/devtoys/Plugins/DevToys.Tools'...
2024-07-25T16:57:42.2868721+02:00	Information	[DevToys.Core.Mef.MefComposer]	[LogMefComposition]	MEF composed 112 parts from 6 assemblies in 89.9143ms
2024-07-25T16:57:42.3007829+02:00	Information	[DevToys.Linux.LinuxProgram]	[2]	MEF, services and logging initialized in 359.9029 ms
2024-07-25T16:57:42.3008296+02:00	Information	[DevToys.Linux.LinuxProgram]	[1]	App is starting...
2024-07-25T16:57:42.3255509+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Base64ImageEncoderDecoder' tool instance manager.
2024-07-25T16:57:42.3256098+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Base64TextEncoderDecoder' tool instance manager.
2024-07-25T16:57:42.3256133+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'CertificateDecoder' tool instance manager.
2024-07-25T16:57:42.3256149+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'ColorBlindnessSimulator' tool instance manager.
2024-07-25T16:57:42.3256173+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'CronParser' tool instance manager.
2024-07-25T16:57:42.3256190+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'DateConverter' tool instance manager.
2024-07-25T16:57:42.3256215+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'EscapeUnescape' tool instance manager.
2024-07-25T16:57:42.3256238+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'GZipEncoderDecoder' tool instance manager.
2024-07-25T16:57:42.3256254+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'HashAndChecksumGenerator' tool instance manager.
2024-07-25T16:57:42.3256269+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'HtmlEncoderDecoder' tool instance manager.
2024-07-25T16:57:42.3256291+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'ImageConverter' tool instance manager.
2024-07-25T16:57:42.3256305+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonFormatter' tool instance manager.
2024-07-25T16:57:42.3256319+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JSONPathTester' tool instance manager.
2024-07-25T16:57:42.3256351+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonTableConverter' tool instance manager.
2024-07-25T16:57:42.3256366+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonWebTokenEncoderDecoder' tool instance manager.
2024-07-25T16:57:42.3256379+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'JsonYamlConverter' tool instance manager.
2024-07-25T16:57:42.3256404+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'ListCompare' tool instance manager.
2024-07-25T16:57:42.3256419+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'LoremIpsumGenerator' tool instance manager.
2024-07-25T16:57:42.3256432+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'MarkdownPreview' tool instance manager.
2024-07-25T16:57:42.3256455+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'NumberBaseConverter' tool instance manager.
2024-07-25T16:57:42.3256469+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'PasswordGenerator' tool instance manager.
2024-07-25T16:57:42.3256482+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'QRCodeEncoderDecoder' tool instance manager.
2024-07-25T16:57:42.3256504+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'RegExTester' tool instance manager.
2024-07-25T16:57:42.3256518+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'SqlFormatter' tool instance manager.
2024-07-25T16:57:42.3256531+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'TextAnalyzerAndUtilities' tool instance manager.
2024-07-25T16:57:42.3256556+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'TextCompare' tool instance manager.
2024-07-25T16:57:42.3256569+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'UrlEncoderDecoder' tool instance manager.
2024-07-25T16:57:42.3256581+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'UUIDGenerator' tool instance manager.
2024-07-25T16:57:42.3256607+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'XmlFormatter' tool instance manager.
2024-07-25T16:57:42.3256620+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'XMLTester' tool instance manager.
2024-07-25T16:57:42.3262307+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Extensions Manager' tool instance manager.
2024-07-25T16:57:42.3262402+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'Settings' tool instance manager.
2024-07-25T16:57:42.3265401+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInitialized]	Initialized 'NoSearchResults' tool instance manager.
2024-07-25T16:57:42.3280013+02:00	Information	[DevToys.Core.Tools.GuiToolProvider]	[LogToolInstancesCreated]	Instantiated 32 tools in 4.6763ms
2024-07-25T16:57:43.1126071+02:00	Information	[DevToys.Blazor.Core.Services.FontService]	[LogImportThirdPartyFontsAsync]	Loaded 2 font(s) in 13.383 ms and injected them in 184.0107 ms
2024-07-25T16:57:43.1190290+02:00	Error	[DevToys.Tools.SmartDetection.YamlDataTypeDetector]	[0]	Invalid data detected.
While scanning a plain scalar value, found invalid mapping.
(Line: 1, Col: 26, Idx: 25) - (Line: 1, Col: 26, Idx: 25): While scanning a plain scalar value, found invalid mapping.

2024-07-25T16:57:43.1283660+02:00	Information	[DevToys.Core.Settings.SettingsProvider]	[LogSetSetting]	Setting 'DevToys.Tools.MarkdownPreviewGuiTool.theme' changed to 'Light'
2024-07-25T16:57:43.1286369+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInstanceCreated]	Instance of 'MarkdownPreview' tool created.
2024-07-25T16:57:43.1641710+02:00	Information	[DevToys.Core.Settings.SettingsProvider]	[LogSetSetting]	Setting 'DevToys.Core.RecentTool3' changed to ''
2024-07-25T16:57:43.1643126+02:00	Information	[DevToys.Core.Settings.SettingsProvider]	[LogSetSetting]	Setting 'DevToys.Core.RecentTool2' changed to 'Settings'
2024-07-25T16:57:43.1643236+02:00	Information	[DevToys.Core.Settings.SettingsProvider]	[LogSetSetting]	Setting 'DevToys.Core.RecentTool1' changed to 'MarkdownPreview'
2024-07-25T16:57:43.1643778+02:00	Information	[DevToys.Core.Tools.GuiToolProvider]	[LogSetMostRecentUsedTool]	Set 'MarkdownPreview' as the most recently used tool.
2024-07-25T16:57:43.3104892+02:00	Error	[DevToys.Core.Web.WebClientService]	[0]	Error while fetching data from https://api.nuget.org/v3-flatcontainer/DevToys.Tools/index.json
Response status code does not indicate success: 404 (The specified blob does not exist.).
System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (The specified blob does not exist.).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at DevToys.Core.Web.WebClientService.SafeGetStringAsync(Uri uri, CancellationToken cancellationToken) in /home/etienne/Documents/repos/Publish/submodules/DevToys/src/app/dev/DevToys.Core/Web/WebClientService.cs:line 22

2024-07-25T16:57:51.1600797+02:00	Information	[DevToys.Core.Settings.SettingsProvider]	[LogSetSetting]	Setting 'DevToys.Core.RecentTool2' changed to 'MarkdownPreview'
2024-07-25T16:57:51.1602263+02:00	Information	[DevToys.Core.Settings.SettingsProvider]	[LogSetSetting]	Setting 'DevToys.Core.RecentTool1' changed to 'Settings'
2024-07-25T16:57:51.1602707+02:00	Information	[DevToys.Core.Tools.GuiToolProvider]	[LogSetMostRecentUsedTool]	Set 'Settings' as the most recently used tool.
2024-07-25T16:57:51.1620916+02:00	Information	[DevToys.Core.Tools.GuiToolInstance]	[LogInstanceCreated]	Instance of 'Settings' tool created.
```

**Comment by badcel** [comment]
Please refer to #1198

**Comment by giosal** [comment]
Confirmed that workaround works on both 24.04 and 24.10 daily
